aigoya/src/App.js
aigoya/src/component/mainWeather.jsx
aigoya/src/css/mainWeather.module.css
aigoya/src/page/mainPage.js

- [x ] 🎯 새로운 기능 (feat)
날씨 컴포넌트 틀 구현
Closes #3 
- [ x] 코드가 정상적으로 빌드됨
- [ x] 기본 기능이 정상 동작함
- [ x] 다른 기능에 영향을 주지 않음
- [ x] 필요없는 주석 및 코드 삭제했는가

feat: 날씨 컴포넌트 틀 구현

---

aigoya/src/component/mainChart.js
aigoya/src/css/mainChart.module.css
aigoya/src/css/mainPage.module.css

메인 화면에 들어갈 시간대별 매출 현황 컴포넌트의 큰 틀 구현
x
Closes #8

feat: 시간대별 매출 현황 컴포넌트 큰 틀 구현

---

aigoya/package-lock.json
aigoya/package.json
aigoya/src/component/mainPopularMenu.jsx
aigoya/src/component/mainUnpopularMenu.jsx
aigoya/src/css/mainPopularMenu.module.css
aigoya/src/css/mainUnpopularMenu.module.css
aigoya/src/page/mainPage.js

 style: 인기 메뉴, 주간 비인기메뉴 컴포넌트 틀 디자인 수정

---

aigoya/src/component/mainChart.jsx
aigoya/src/page/mainPage.jsx

기존 차트의 모양을 꺾은선형 모양으로 변경
메인 페이지에 컴포넌트 추가
x
x

refactor: 차트 모양 변경

---

aigoya/src/App.js
aigoya/src/component/mainChart.jsx
aigoya/src/component/mainChatBot.jsx
aigoya/src/css/chatBotPage.module.css
aigoya/src/css/mainChart.module.css
aigoya/src/css/mainChatBot.module.css
aigoya/src/css/mainPage.module.css
aigoya/src/index.js
aigoya/src/page/chatBotPage.jsx
aigoya/src/page/mainPage.jsx

챗봇 컴포넌트, 챗봇 페이지 생성 및 기초 css 작업 완료
메인 페이지에서 메시지를 선택하거나 전송 버튼을 누르면 챗봇 페이지로 이동하여 대화 시작
api 연동 필요
x
Closes #11
Closes #12

feat: 챗봇 컴포넌트, 챗봇 페이지 생성 및 기초 css 작업 완료

---

aigoya/src/App.js
aigoya/src/page/loginPage.jsx

로그인 페이지 라우터 설정
로그인 파일 구조 변경
x
x
x

refactor: 로그인 페이지 라우터 설정 및 파일 구조 변경

---

aigoya/src/css/mainPage.module.css
aigoya/src/page/mainPage.jsx

- [] 🎯 새로운 기능 (feat)
- [] 🐞 버그 수정 (fix)
- [] 🎨 디자인/스타일 (design)
- [] 📝 문서 (docs)
- [] 🔧 기타 (chore)
메인 페이지 내의 컴포넌트들 1차 배치
x
Relates to #10

refactor: 메인 페이지 컴포넌트 배치

---

aigoya/package-lock.json
aigoya/package.json
aigoya/src/component/header.jsx
aigoya/src/component/mainSales.jsx
aigoya/src/css/header.module.css
aigoya/src/css/mainSales.module.css
aigoya/src/page/mainPage.jsx

feat: 헤더 1차 생성

---

aigoya/src/App.css
aigoya/src/css/mainPage.module.css

메인페이지 컴포넌트의 background-color 값을 app.css의 body로 이동
Closes #40

style: 전역스타일 body 색상 변경

---

aigoya/src/App.js
aigoya/src/css/mainPage.module.css
aigoya/src/css/posMachinePage.module.css
aigoya/src/page/mainPage.jsx
aigoya/src/page/posMachinePage.jsx

메인 페이지에 포스기 연결 버튼 생성 및 포스기 페이지 구현
Closes #45 
Before
After
메인 페이지에 포스기 페이지 연결 버튼 생성
포스기 페이지 생

feat: 포스기 페이지 구현

---

aigoya/src/api/storeApi.js
aigoya/src/css/loginPage.module.css
aigoya/src/page/loginPage.jsx
aigoya/src/page/mainPage.jsx

로그인 유지 체크 -> 로그아웃 누르기 전까지 세션 유지 가능
로그인 유지 체크 x -> 탭 닫으면 즉시 세션 초기화
(공통) 로그인 상태일 때 - > url을 "/" (로그인화면) 돌아가려하면 다시 "/main"으로 돌아오도록
Closes #50 #30

refactor: 로그인 상태 리다이렉트 설정

---

.github/workflows/deploy.yml
aigoya/Dockerfile
aigoya/Dockerfile.dev

- 도커 파일 설정
- 깃허브 액션 설정 테스트
x
Relates to #54 
x

chore: 배포 및 깃액션 테스트1

---

aigoya/src/api/productManagementApi.js
aigoya/src/api/storeApi.js
aigoya/src/css/posMachinePage.module.css
aigoya/src/page/posMachinePage.jsx

포스기 화면에서 사용 가능 하도록 API 연결
403 권한 문제가 생기는데 혹시 뭐 때문인지 봐주세요
Relates #52

feat: 포스기 상품관리 api 연결

---

aigoya/src/api/StoreApi.js
aigoya/src/component/MainSales.jsx
aigoya/src/css/MainSales.module.css

매출 컴포넌트 API 연결 완료
4번째 부분 아직 나오지 않아서 매출 컴포넌트 3개 부분만 넣어놓음
Relates to #44

feat: 매출 컴포넌트 API연결

---

aigoya/src/css/PosMachinePage.module.css
aigoya/src/page/PosMachinePage.jsx

pos기 화면에서 메인 화면으로 가는 'pos종료'버튼 생성
종료 버튼 색상 변경 필요
Closes #75

Feat: pos종료 버튼 생성

---

aigoya/src/App.js
aigoya/src/component/SideBar.jsx
aigoya/src/css/MyPage.module.css
aigoya/src/css/OrderList.module.css
aigoya/src/page/OrderList.jsx

기존 포스기에서만 주문과 매출을 확인할 수 있었지만, 따로 페이지를 구분하여 매출 관리 페이지 생성
x
Closes #80

feat: 매출관리 페이지 생성

---

aigoya/src/api/StoreApi.js
aigoya/src/component/MainPopularMenu.jsx
aigoya/src/component/MainUnpopularMenu.jsx

일별 인기메뉴 , 주간별 비인기메뉴 api 연결
Closes #28

refactor: 일별 인기, 주별 비인기 메뉴 api 연결

---

aigoya/src/api/StoreApi.js
aigoya/src/page/SignUpPage.jsx

보안을 위한 회원가입 api 주석 처리
x
Closes #79 
x

refactor: 회원가입 주석 처리

---

aigoya/src/App.js
aigoya/src/api/StoreApi.js
aigoya/src/component/SideBar.jsx
aigoya/src/css/EmployeePage.module.css
aigoya/src/page/EmployeePage.jsx

feat: 직원 관리 페이지 생성

---

aigoya/src/css/PosMachinePage.module.css
aigoya/src/page/PosMachinePage.jsx

주문 완료 후 뜨는 모달에서 메뉴 이름 길이와 상관없이 수량의 위치가 동일 하도록 정렬
Closes #88 
Before
After

design: 주문완료 후 모달 수량 위치 정렬

---

aigoya/src/api/StoreApi.js
aigoya/src/page/ChatBotPage.jsx

챗봇 api 연결 실패하던 문제 수정
x
Relates to #73 
x

refactor: 챗봇 api 수정

---

aigoya/src/api/StoreApi.js
aigoya/src/component/MainChart.jsx
aigoya/src/component/MainPopularMenu.jsx
aigoya/src/component/MainSales.jsx
aigoya/src/component/MainUnpopularMenu.jsx
aigoya/src/component/MainWeather.jsx
aigoya/src/css/Header.module.css
aigoya/src/page/ChatBotPage.jsx
aigoya/src/page/EmployeePage.jsx
aigoya/src/page/LoginPage.jsx
aigoya/src/page/OrderList.jsx
aigoya/src/page/PosMachinePage.jsx

전체 파일 불필요한 주석 제거
Closes #이슈번호
Relates to #이슈번호

refactor: 파일 전체 불필요한 주석 제거
